version: "3"

services:
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony
        ports:
            - 80:80
        networks:
            - symfony_app
        env_file:
            - .env.nginx.local
    php:
        user: ${UID}:${UID}
        build:
            context: ./php
            args:
                UID: ${UID}
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony
        networks:
            - symfony_app
    db:
        image: mysql:8.0.35
        platform: linux/arm64/v8
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3307:3306
        networks:
            - symfony_app
    phpmyadmin:
        image: phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - 8081:80
        networks:
            - symfony_app

volumes:
    db_app:


networks:
    symfony_app:
