controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


api_login_check:
    path: /api/login_check

liste:
    path: /api/liste


signup:
    path: /api/signup
    controller: App\Controller\UserController::signup
    methods: [GET, POST] 

token:
    path: /api/token
    controller: App\Controller\UserController::getTokenUser
    methods: [GET, POST] 

jwt_refresh:
    path: /api/token/refresh
    controller : gesdinet.jwtrefreshtoken::refresh
    methods: [GET, POST] 
